// Package feeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package feeder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /daemon/ping)
	PostDaemonPing(ctx echo.Context) error

	// (POST /daemon/status)
	PostDaemonStatus(ctx echo.Context) error

	// (POST /instance/action)
	PostInstanceAction(ctx echo.Context) error

	// (PUT /instance/action)
	PutInstanceActionEnd(ctx echo.Context) error

	// (POST /instance/resource_info)
	PostInstanceResourceInfo(ctx echo.Context) error

	// (POST /instance/status)
	PostInstanceStatus(ctx echo.Context, params PostInstanceStatusParams) error

	// (POST /node/disk)
	PostNodeDisk(ctx echo.Context) error

	// (POST /node/system)
	PostSystem(ctx echo.Context) error

	// (POST /object/config)
	PostObjectConfig(ctx echo.Context) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonPing(ctx)
	return err
}

// PostDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonStatus(ctx)
	return err
}

// PostInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceAction(ctx)
	return err
}

// PutInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutInstanceActionEnd(ctx)
	return err
}

// PostInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceResourceInfo(ctx)
	return err
}

// PostInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceStatus(ctx, params)
	return err
}

// PostNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeDisk(ctx)
	return err
}

// PostSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSystem(ctx)
	return err
}

// PostObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostObjectConfig(ctx)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/daemon/ping", wrapper.PostDaemonPing)
	router.POST(baseURL+"/daemon/status", wrapper.PostDaemonStatus)
	router.POST(baseURL+"/instance/action", wrapper.PostInstanceAction)
	router.PUT(baseURL+"/instance/action", wrapper.PutInstanceActionEnd)
	router.POST(baseURL+"/instance/resource_info", wrapper.PostInstanceResourceInfo)
	router.POST(baseURL+"/instance/status", wrapper.PostInstanceStatus)
	router.POST(baseURL+"/node/disk", wrapper.PostNodeDisk)
	router.POST(baseURL+"/node/system", wrapper.PostSystem)
	router.POST(baseURL+"/object/config", wrapper.PostObjectConfig)
	router.GET(baseURL+"/openapi.json", wrapper.GetSwagger)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W8buRH/Vwi2D1dgz1Ls9KF6c+6SIi1wSa279sFnCBR3tOJll2RIrmxdoP+94Nd+",
	"SFyt7FjGAbkn2+TsfPzmx+HsrL9gKiopOHCj8ewLlkSRCgwo9xfj/6lBbedbTv2feIY/2xWcYU4qwDOs",
	"7V6GNV1DRayQ2Uq7vhSiBMLxbrfLsAItBdfglL6eTu0PKrgBbuyvRMqSUWKY4JPftOB2rVX4VwUrPMN/",
	"mbSeTvyunnxUYllC5a3koKli0qrBM/yG5OgGPtegDd5l+PX01UtY/YWT2qyFYr9D7s1evYTZd0ItWZ4D",
	"tzb//jIAv+cGFCclmoPagEJvlRLK2v+RQCX4R8aLa0pBGsgf5Y5UQoIyzLNFLH8Dahb3zKxFbRZU8BUr",
	"7EbfmZJpg8QKeXFkyamRWRODFHyumQKNPn6Y/4wmRLKJF5oEXRlmBip9qLOjC2eR19ooxgsbZlggSpEt",
	"3rUL/rEUYrkDBmlDTK2RYRVoQyqp0T0rS7QEpGClQK8hRyuhEBc5tHjO3VN/InoE0WMw7mKNcm5dU69g",
	"HxvSrB84R1SxcUUwhjbifoaXUDB+CIJbRt5SSwLEOLp598PV1dU/fiJcWM8rYlIoUdXzsCm0GQaeH5oD",
	"nn+FMUnMOhmsBq2Z4Iu6ZnlawOXkyNaiFEVye1DlBpQO6enHaNaAhASuNxTRkgE3KCeGoPjAQWDuTnIs",
	"zvHs1keZxey3hmIOA+h7UQdOBIc9/FFJKYoVKy3LAw53B2zOAgvDJdU92X1SDuCxF4OTSln5kelPh0rz",
	"NPYDyFcihzK5E6rJIE8UFEMnSrPfwW4E9s0w4+bqsk0W4wYKcFdKraHrWGdnAzwXahwel6Gus8F+0N0o",
	"irFmFqEUnO+5NoRTuAEtakXhPV+JQ3hZWG2qRX/7E2z18e30ASBlDeOx2sejcCqE/UKlTuGXcgg6x0/R",
	"OUgII6QoRbEdtxjS5KA8lol5U2n2KE5MtyNtHxz07dwFxnnUmkkF9ZPIwZ7YI/E0pDnWuLlTf8KdmuEP",
	"7rcfmjZg70aUMgkVFVUVmo+DvVzJhbt1j23qx12mwDdJuVUJD4uKPKSrg99l/MiuIaoAkxaoBGdGKMgX",
	"Kpz2BRU1H5AWiq5BG0VMOvLhGknuO21YUw6XW5NskzQVEh6H3iMPXYqYH4U2bWd/SJQmp+k2kpa1NhC6",
	"scEGsSt1YpsYq/oJtrut7DM1qWesGR7QNrzjdaNNz1A5pGvCi71jl4xcKMRCaT0FgOEyq2DDRK0XtcyJ",
	"gXxBTI/fdvF725OmrDzlmbOlItTtiOBIJsIr80ECDDyYQ9+u0bquCP9eAcnJsgQED7Ik3L3LIS2BshWj",
	"yAhk1kwjQWmtFHAKlthmDb9y6e1d/Doeh/Mg5bMk9BMpIFH+FU3XLMeQsnxkhvzQKNkLFkcK2fGreuQY",
	"+XPcptqFFDR7wylE9FabVBI7SJ10D0f5k67iTlB9q50NeCCVLO1z04vpxavRnA9T1b3F0Voxs51bb72p",
	"JdGMXtf+qnJRuLdMu9raWhsj/SsuUaCitP/rXWTCv/73c5wMOhVud1/Hbpc1zbJhxgUWj+oKIAeFiGSd",
	"BM7wlYvbFn4J3G76pSn2V6yLYuInAxMZ7yqhE2fvxg8KmgtiaEDjjpbNhzuV73M8278OPeagzRuRb59v",
	"+tY3suvn1qga9oerl9PLIaWN3CQxoNtl+HL6+hChimnNeLGHTByrZGEEFMAOu0yjxskuyfDstkev27td",
	"9qVHodu7naUpKbRlLiksgHdWRd/CExN6NIvh1jx3HoOZ583k3mjQjZ2n4w9boXYyPib7qjPOHpO96oyh",
	"j8taoefiSGxaJu0UL82SN34C1wzhLJ0JKtgGeOwRbSEZ4Et87byO06JzMCYoP50nz2h1fyCVmLsG4OIo",
	"8xsmXoZlnaDYW54/jWD1Hr/euqHiH4JiSQr48fKflcdXnmZMEFuadAH6xb3c2BctqsD+FhWgqABZBSMF",
	"qDeBPA9Hkqaeyph0kLZZtEQ6+Hjz/NkZ6x7mRqj2RfHy4lWbl9Da2BfBi5G0NJ1E91v6bRrnVmTS/dZu",
	"IzlnOh/ThUyPJDKgot2MDOmaUtB6VZflFn2nt5yuleCi1n/z7eXluKb2y12sKeg7sq/pmywxtt2e5PFT",
	"zmlVxU3R7DMa+fFi7Sk7QOA4ej5TLWkn208tIEPxnLF2ONg7s4Ak8BY85IWse1RsQG0HQJ57XeeBODj6",
	"VHxjCMSQkX9J+CaPYP+fHE4/hqHjO+UI9r7FnIcjPRNffZW/1DkMo56LGGv4ZNNH8J9g5vekKNyUKXWN",
	"nQzg6D+efPj3H4baES5ZL0tGA16dgWGAqu+/AlMrjohknSH4AZr/bba+Cs1jdIzWBzF+EhaUSLJkJXPz",
	"07udZ6HaxFasViWe4YsJ3t3t/h8AAP//0x1mAAIpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
